---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-comparison-db-deployment
  labels:
    app: car-comparison-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-comparison-db
  template:
    metadata:
      labels:
        app: car-comparison-db
    spec:
      containers:
        - name: car-comparison-db
          image: redis:6
          ports:
          - name: http
            containerPort: 6379
          volumeMounts:
          - name: data
            mountPath: "/data"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
