FROM centos:7.9.2009

RUN yum update -y && \
    yum install -y python3

RUN mkdir /app
RUN pip3 install --user pandas
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

COPY . /app

ENTRYPOINT ["python3"]
CMD ["app.py"]
