FROM python:3.9

COPY requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt

COPY ./src/* /app/
COPY ./fuel_ratings.csv /app/fuel_ratings.csv

WORKDIR /app/
ENTRYPOINT ["python3"]
CMD ["app.py"]
