FROM python:3.9

RUN pip3 freeze > requirements.txt
RUN pip3 install --user -r requirements.txt

COPY ./src/* /app/
COPY ./fuel_ratings.csv /app/fuel_ratings.csv

WORKDIR /app/
ENTRYPOINT ["python3"]
CMD ["app.py"]
