---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-comparison-flask-deployment
  labels:
    app: car-comparison-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-comparison-flask
  template:
    metadata:
      labels:
        app: car-comparison-flask
    spec:
      containers:
        - name: car-comparison-flask
          imagePullPolicy: Always
          image: sloats/car-comparison:0.1
          env:
          - name: REDIS_IP
            value: "127.0.0.1"
          ports:
          - name: http
            containerPort: 5000
