---
apiVersion: v1
kind: Service
metadata:
  name: car-comparison-api-service
spec:
  type: ClusterIP
  selector:
    app: car-comparison-api
  ports:
  - name: car-comparison-api
    port: 5000
    targetPort: 5000
