---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuel-emissions-db-deployment
  labels:
    app: fuel-emissions-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fuel-emissions-db
  template:
    metadata:
      labels:
        app: fuel-emissions-db
    spec:
      containers:
        - name: fuel-emissions-db
          image: redis:6
          ports:
          - name: http
            containerPort: 6379
          volumeMounts:
          - name: data
            mountPath: "/data"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
