---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuel-consumption-wrk-deployment
  labels:
    app: fuel-consumption
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fuel-consumption
  template:
    metadata:
      labels:
        app: fuel-consumption
    spec:
      containers:
        - name: fuel-consumption
          imagePullPolicy: Always
          image: sloats/app-wrk:0.1
          env:
          - name: REDIS_IP
            value: "127.0.0.1"